name = "MyProject"
version = "0.1.0"
defaultTargets = ["myproject"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"

[[lean_lib]]
name = "MyProject"

[[lean_exe]]
name = "myproject"
root = "Main"
